<?php

return [
    'default_role' => 'standard',

    'role_priority' => [
        'creator',
        'admin',
        'premium',
        'standard',
    ],

    'roles' => [
        'standard' => [
            'allowed_topics' => [
                'aniyume_help',
                'platform_content',
                'own_profile',
                'own_watch_history',
                'own_favorites',
                'own_ratings',
                'own_comments',
            ],
            'allowed_tools' => [
                'anime.search',
                'user.profile_summary',
                'user.anime_list',
            ],
            'response_strictness' => 'strict',
            'rate_limit_tier_hint' => 'standard',
            'personal_data_scope' => 'self',
            'allow_admin_data' => false,
            'allow_system_data' => false,
            'allow_out_of_domain' => false,
        ],

        'premium' => [
            'allowed_topics' => [
                'aniyume_help',
                'platform_content',
                'recommendations',
                'own_profile',
                'own_watch_history',
                'own_favorites',
                'own_ratings',
                'own_comments',
                'premium_features',
            ],
            'allowed_tools' => [
                'anime.search',
                'user.profile_summary',
                'user.anime_list',
                'recommendation_context',
            ],
            'response_strictness' => 'balanced',
            'rate_limit_tier_hint' => 'premium',
            'personal_data_scope' => 'self',
            'allow_admin_data' => false,
            'allow_system_data' => false,
            'allow_out_of_domain' => false,
        ],

        'admin' => [
            'allowed_topics' => [
                'aniyume_help',
                'platform_content',
                'recommendations',
                'own_profile',
                'own_watch_history',
                'own_favorites',
                'own_ratings',
                'own_comments',
                'admin_operations',
                'moderation',
                'import_status',
                'aggregate_platform_metrics',
            ],
            'allowed_tools' => [
                'anime.search',
                'user.profile_summary',
                'user.anime_list',
                'recommendation_context',
                'admin.dashboard_summary',
                'moderation_context',
            ],
            'response_strictness' => 'balanced',
            'rate_limit_tier_hint' => 'admin',
            'personal_data_scope' => 'self_and_operational_metadata',
            'allow_admin_data' => true,
            'allow_system_data' => true,
            'allow_out_of_domain' => false,
        ],

        'creator' => [
            'allowed_topics' => [
                'aniyume_help',
                'platform_content',
                'recommendations',
                'own_profile',
                'own_watch_history',
                'own_favorites',
                'own_ratings',
                'own_comments',
                'admin_operations',
                'moderation',
                'import_status',
                'aggregate_platform_metrics',
                'creator_operations',
                'policy_debug_summary',
            ],
            'allowed_tools' => [
                'anime.search',
                'user.profile_summary',
                'user.anime_list',
                'recommendation_context',
                'admin.dashboard_summary',
                'moderation_context',
                'creator_summary_context',
                'policy_introspection',
            ],
            'response_strictness' => 'policy-aware',
            'rate_limit_tier_hint' => 'creator',
            'personal_data_scope' => 'self_and_operational_metadata',
            'allow_admin_data' => true,
            'allow_system_data' => true,
            'allow_out_of_domain' => false,
        ],
    ],

    'global_denied_topics' => [
        'secrets',
        'env_values',
        'system_prompt_disclosure',
        'raw_database_structure',
        'other_users_personal_data',
        'credential_or_token_access',
        'unrestricted_general_answers',
    ],

    'domain_boundaries' => [
        'AniYume platform help',
        'AniYume content, anime catalog, episodes, tags, comments, ratings and recommendations',
        'The authenticated user personal AniYume data only when scoped to that same user',
        'Administrative or system summaries only for admin and creator AI roles',
    ],
];
